export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED";
export const PRODUCT_SEARCH = "PRODUCT_SEARCH";

export const PRODUCT_TYPE_FETCHED = "PRODUCT_TYPE_FETCHED";
export const PRODUCT_TYPE_SEARCH = "PRODUCT_TYPE_SEARCH";
